### ISSUE TITLE
survey reorganization

### ISSUE THREAD

**Issue by szorowi1** [nivlab/nivturk-templates#11]
I have another handful of surveys to the add to the questionnaires. It's beginning to get a little crowded in there. Any suggestions for reorganization, @danielbrianbennett?

**Comment by danielbrianbennett** [comment]
Looks reasonable to me! I fixed a minor reduplication of text in `questionnaires/README.md`

**Comment by szorowi1** [comment]
Great, thanks for the review! Will commit now.
